### ISSUE TITLE
Plugin is not compatible with PHP 5.3/5.4

### ISSUE THREAD

**Issue by ocean90** [wearerequired/digest#14]
https://github.com/wearerequired/digest/blob/33576d11f3846df311c6c3be260c93111e398f77/digest.php#L83

`ClassName::class` is only available in PHP 5.5+.

Not sure if we should bump the minimum supported version or just use `Required\Digest\Cron`.

**Comment by ocean90** [comment]
https://github.com/wearerequired/digest/blob/33576d11f3846df311c6c3be260c93111e398f77/digest.php#L2 will also cause a parse error in PHP 5.2.

**Comment by swissspidy** [comment]
Yeah I the main plugin file needs to be update massively before this is going to be released publicly. In other plugins I've added an `init.php` file before, but a `bootstrap.php` inside `inc` (now `classes`) would work, too. Human Made do this according to their handbook and it's quite easy to grasp.

Regarding the overall PHP version, I don't care that much if it's gonna be 5.5+ or not.

**Comment by neverything** [comment]
Do you have a link for this portion of the handbook?

**Comment by swissspidy** [comment]
Okay, it's not `bootstrap.php` but `namespace.php`. There's `bootstrap()` though for simple files.

@neverything It's in https://engineering.hmn.md/how-we-work/style/php/ (File Layout and File Naming)

**Comment by swissspidy** [comment]
So I began working on this in the `14-namespace` branch, just to see how feasible it is.

From a structure point of view it looks nice. Now I just need a way to make the event registry available again as a single object to the template functions like `digest_register_event()` & co. Before that, it was easy because it was more or less a dependency injection thing.

Suggestions welcome.

**Comment by grappler** [comment]
Increased minimum PHP to 5.6 in #18
